version: '3.8'

services:
  db:
    image: postgres:15
    container_name: exchange_rate_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: currency_db
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: exchange_rate_backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: exchange_rate_frontend
    ports:
      - "4200:80" # Mapujemy port 80 Nginxa na Twoje 4200
    depends_on:
      - backend